### ISSUE TITLE
기본형 변수(double) 초기화 한 경우 초기값

### ISSUE THREAD

**Issue by kha212** [pej4303/java-study#1]
double(0.0 or 0.0d) 이라고 하는데, OS 마다 다른 것인지 JVM 버전마다 다른 것인지 확인 필요

**Comment by pej4303** [comment]
아래의 링크에서 primitive 타입에 대한 기본값 내용이 있는데 OS 또는 JVM 버전별로 다르다는 내용은 없음.
 + https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html


Data Type | Default Value (for fields)
-- | --
byte | 0
short | 0
int | 0
long | 0L
float | 0.0f
double | 0.0d
char | '\u0000'
String (or any object) | null
boolean | false


</body>
</html>
