### ISSUE TITLE
초기화 블럭 사용하지 않는 이유

### ISSUE THREAD

**Issue by kha212** [pej4303/java-study#2]
프로젝트를 하면서 초기화 블럭을 사용하는 것을 보지 못하였다. 보편적으로 사용하지 않는 이유에 대한 토론 필요할듯

**Comment by pej4303** [comment]
공통 소스에서 사용된 예를 찾았으나 대부분 new 연산자를 사용해서 인스턴스 생성을 하거나 배열 정렬을 사용하는 정도로만 되어있었다. 복잡한 초기화 작업을 하는 경우 많지 않아서 거의 사용하지 않는 것이 아닐까라는 생각이 든다.

```
private static String[] arr = {"02", "070", "080", "032", "031"};

static {
   Arrays.sort(arr);
}
```
